/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import itp.DBconnect;
import java.sql.*;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Date;

/**
 *
 * @author Trishan
 */
public class Insert extends Perent {

    Connection con = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Insert
     */
    public Insert() {
        initComponents();

        con = DBconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSciName = new javax.swing.JTextField();
        Category = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        CompName = new javax.swing.JTextField();
        RackNo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 700));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/home.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 73, 60);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Profile");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(650, 10, 50, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("<html>Hello michika<br> level : Admin </html>");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(640, 30, 100, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Logout");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(650, 70, 50, 20);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/admin1.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(750, 10, 60, 80);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(0, 660, 820, 20);

        jLabel11.setBackground(new java.awt.Color(255, 51, 0));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Notification Bar");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 640, 830, 20);

        jLabel6.setText("Expire Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 410, 140, 14);

        jLabel2.setText("Scientific Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 224, 130, 10);

        jLabel4.setText("Category");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 260, 160, 14);

        jLabel3.setText("Quantity");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 300, 140, 14);

        jLabel5.setText("Company Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 340, 160, 14);

        jLabel1.setText("Medicine Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 190, 160, 14);

        txtMedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtMedName);
        txtMedName.setBounds(530, 190, 140, 20);

        jLabel8.setText("Rack Number");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 450, 150, 14);

        jLabel7.setText("Manufacture Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 370, 150, 17);
        getContentPane().add(txtSciName);
        txtSciName.setBounds(530, 220, 140, 20);
        getContentPane().add(Category);
        Category.setBounds(530, 260, 140, 20);
        getContentPane().add(Quantity);
        Quantity.setBounds(530, 290, 140, 20);
        getContentPane().add(CompName);
        CompName.setBounds(530, 330, 140, 20);

        RackNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RackNoActionPerformed(evt);
            }
        });
        getContentPane().add(RackNo);
        RackNo.setBounds(530, 450, 140, 20);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 590, 55, 23);

        jButton3.setText("Insert");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(740, 590, 61, 23);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(530, 370, 140, 20);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(530, 410, 140, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 98, 830, 0);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(220, 20, 0, 2);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 100, 0, 2);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 90, 830, 20);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Insert Medicine");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 30, 141, 26);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/11806788_1135526379794041_692436290_o.jpg"))); // NOI18N
        jLabel23.setText("jLabel23");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 830, 690);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedNameActionPerformed

    private void RackNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RackNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RackNoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        main m3 = new main();
        m3.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        

        if (txtMedName.getText().isEmpty() || txtSciName.getText().isEmpty() || Category.getText().isEmpty() || Quantity.getText().isEmpty() || CompName.getText().isEmpty() ||  RackNo.getText().isEmpty() || ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()
 ||     ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText().isEmpty())
 {
            JOptionPane.showMessageDialog(this, "No text field should be empty");

            return;

        }
        try {
            int x = Integer.parseInt(Quantity.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid Quantity");
            Quantity.setText("");

        }

        try {
            int y = Integer.parseInt(RackNo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid rack number");
            RackNo.setText("");
        }

        try {
            String Medicine_Name = txtMedName.getText();
            String Scientific_Name = txtSciName.getText();
            String Product_Category = Category.getText();
            String quantity = Quantity.getText();
            String Company_Name = CompName.getText();
            String Rack_Number = RackNo.getText();
            SimpleDateFormat javadate = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
            String manu_date = javadate.format(jDateChooser1.getDate());
            String exp_date = javadate.format(jDateChooser2.getDate());
            //Date d = new Date();
            //System.out.println(d.getDate() - jDateChooser1.getDate().getDate());

            String q = "INSERT INTO stock (Medicine_Name,Scientific_Name,Product_Category,Quantity,Company_Name,Rack_Number,Manufacure_Date, Expire_Date) values ('" + Medicine_Name + "' , '" + Scientific_Name + "' , '" + Product_Category + "' , '" + quantity + "' ,'" + Company_Name + "' , '" + Rack_Number + "', '" + manu_date + "', '" + exp_date + "' ) ";
            pst = con.prepareStatement(q);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Successfully Inserted");

            txtMedName.setText("");
            txtSciName.setText("");
            Category.setText("");
            Quantity.setText("");
            CompName.setText("");
            RackNo.setText("");
            jDateChooser1.setDate(null);
            jDateChooser2.setDate(null);

        } catch (Exception e) {
            System.out.println(e);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        home.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Category;
    private javax.swing.JTextField CompName;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField RackNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txtMedName;
    private javax.swing.JTextField txtSciName;
    // End of variables declaration//GEN-END:variables
}
