/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import MainWindow.Mainwindow;
import itp.DBconnect;
import java.awt.Component;
import java.sql.*;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.util.Date;

/**
 *
 * @author Alex
 */
public class main extends Perent {
   
    
    //public int id;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rst = null;
    
    
    
   

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        con = DBconnect.connect();

        try {

            String sql = "select Product_Id , Medicine_Name, Scientific_Name, Company_Name, Quantity, Product_Category, Manufacure_Date, Expire_Date, Rack_Number from stock ";
            pst = con.prepareStatement(sql);
            rst = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rst));

        } catch (SQLException e) {
        }
        
        try{
        
            String q2 = " select Product_Id ,Quantity, Expire_Date from stock ";
            
                PreparedStatement pst1 = null;
                ResultSet rst1 = null;
            
             pst1 = con.prepareStatement(q2);
            rst1 = pst1.executeQuery();
            
            Date d = new Date();
            
           
            while(rst1.next()){
            
            
                if(( rst1.getDate(3).getDate() - d.getDate()) <= 30 )
                {
                 
                   // jButton2.setIcon(48);
                
                
                }
                
            }
        
        }
        catch(Exception e){}
        /*SimpleDateFormat javadate = new SimpleDateFormat("yyyy-MM-dd");
            String manu_date = javadate.format(jDateChooser1.getDate());
        Date d = new Date();
        System.out.println(d.getDate()-d.getDate());*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_userinfo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipment Management System");
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(java.awt.SystemColor.activeCaptionText);
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 100, 1020, 10);

        jLabel11.setBackground(new java.awt.Color(255, 51, 0));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Notification Bar");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 550, 1030, 20);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(0, 660, 820, 2);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/admin1.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(950, 10, 60, 80);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Logout");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(840, 80, 50, 20);

        lbl_userinfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_userinfo.setText("<html>Hello michika<br> level : Admin </html>");
        getContentPane().add(lbl_userinfo);
        lbl_userinfo.setBounds(820, 40, 130, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Profile");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(840, 10, 50, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/home.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 73, 60);

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Stock Management System");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 30, 260, 24);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Medicine Name", "Scientific Name", "Companay Name", "Quantity", "Product Categoty", "Manufacture Date", "Expire Date", "Rack Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 210, 880, 220);

        jButton5.setText("Delete Medicine");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(0, 380, 130, 30);

        jButton4.setText("Update Medicine");
        jButton4.setActionCommand("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 330, 130, 30);

        jButton3.setText("Insert Medicine");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 280, 130, 30);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 120, 60, 50);

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(610, 120, 90, 30);

        jButton7.setText("View All");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(3, 230, 130, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(200, 130, 339, 20);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/11806788_1135526379794041_692436290_o.jpg"))); // NOI18N
        jLabel23.setText("jLabel23");
        jLabel23.setPreferredSize(new java.awt.Dimension(2500, 1280));
        getContentPane().add(jLabel23);
        jLabel23.setBounds(-80, 0, 1500, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setVisible(boolean asd){
        super.setVisible(asd);
        lbl_userinfo.setText(hello);
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getSelectedRow() == 0) {
                JOptionPane.showMessageDialog(this, "table is empty");
            } else {
                JOptionPane.showMessageDialog(this, "please select a row");
            }
        } else {
            Update m2 = new Update();
            m2.setVisible(true);
            this.dispose();

            m2.jTextField9.setText(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
            m2.jTextField1.setText((String) model.getValueAt(jTable1.getSelectedRow(), 1));
            m2.jTextField2.setText((String) model.getValueAt(jTable1.getSelectedRow(), 2));
            m2.jTextField3.setText((String) model.getValueAt(jTable1.getSelectedRow(), 3));
            m2.jTextField4.setText(model.getValueAt(jTable1.getSelectedRow(), 4).toString());
            m2.jTextField5.setText((String) model.getValueAt(jTable1.getSelectedRow(), 5));
            m2.jTextField8.setText(model.getValueAt(jTable1.getSelectedRow(), 8).toString());
            m2.Udate.setDate((java.util.Date) (model.getValueAt(jTable1.getSelectedRow(), 6)));
            m2.Edate.setDate((java.util.Date) (model.getValueAt(jTable1.getSelectedRow(), 7)));

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Insert m1 = new Insert();
        m1.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Notifications m5 = new Notifications();
        m5.setVisible(true);
        this.dispose();
        try{
        
            String q2 = " select Product_Id ,Quantity, Expire_Date from stock ";
            
                PreparedStatement pst1 = null;
                ResultSet rst1 = null;
            
             pst1 = con.prepareStatement(q2);
            rst1 = pst1.executeQuery();
            
            Date d = new Date();
            
           
            while(rst1.next()){
            
            
                if(( rst1.getDate(3).getDate() - d.getDate()) <= 30 )
                {
                 System.out.println(rst1.getDate(3).getDate() - d.getDate());
                   // jButton2.setIcon(48);
                  int id1 = rst1.getInt(1);
                  try{
                  String q3 = "select Product_Id , Medicine_Name, Scientific_Name, Company_Name, Quantity, Product_Category, Manufacure_Date, Expire_Date, Rack_Number from stock where Product_Id = '"+ id1 +"'";
                  
                  
                 PreparedStatement pst2 = con.prepareStatement(q3);
                  ResultSet rst2 = pst2.executeQuery();
                  
                  m5.jTable2.setModel(DbUtils.resultSetToTableModel(rst2));
                  
                  }
                  
                  catch(SQLException e ){
                      System.out.println(e+"ddddd");
                  }
                  
                  

                
                }
                
            }
        
        }
        catch(Exception e){}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        con = DBconnect.connect();

        try {

            String sql = "select Product_Id , Medicine_Name, Scientific_Name, Company_Name, Quantity, Product_Category, Manufacure_Date, Expire_Date, Rack_Number from stock ";
            pst = con.prepareStatement(sql);
            rst = pst.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rst));

        } catch (SQLException e) {
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        con = DBconnect.connect();

        String name = jTextField2.getText();
        if(name.equals("")){
            
        JOptionPane.showMessageDialog(this, "Please enter the medicine name");
        return;
        }
        
        try {

            String sql = "select Medicine_Name, Scientific_Name from stock ";
            pst = con.prepareStatement(sql);
            rst = pst.executeQuery();

            while (rst.next()) {

                if (name.equals(rst.getString(1))) {

                    String q = "select Product_Id , Medicine_Name, Scientific_Name, Company_Name, Quantity, Product_Category, Manufacure_Date, Expire_Date, Rack_Number from stock where Medicine_Name= '" + name + "' ";
                    PreparedStatement pst1 = con.prepareStatement(q);
                    ResultSet rst1 = pst1.executeQuery();

                    jTable1.setModel(DbUtils.resultSetToTableModel(rst1));
                    jTextField2.setText("");
                    return;

                } else if (name.equals(rst.getString(2))) {

                    String q = "select Product_Id , Medicine_Name, Scientific_Name, Company_Name, Quantity, Product_Category, Manufacure_Date, Expire_Date, Rack_Number from stock where Scientific_Name= '" + name + "' ";
                    PreparedStatement pst1 = con.prepareStatement(q);
                    ResultSet rst1 = pst1.executeQuery();

                    jTable1.setModel(DbUtils.resultSetToTableModel(rst1));
                    jTextField2.setText("");
                    return;
                }

            }
            JOptionPane.showMessageDialog(this, "There is no such medicine in the stock");
            jTextField2.setText("");

        } catch (Exception e) {
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        con = DBconnect.connect();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getSelectedRow() == 0) {
                JOptionPane.showMessageDialog(this, "table is empty");
            } else {
                JOptionPane.showMessageDialog(this, "please select a row");
            }
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int a = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?","Warning",dialogButton);
            if(a==JOptionPane.YES_OPTION){
                
                int id = Integer.parseInt(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
            try {
                String q = "DELETE FROM stock WHERE Product_Id='" + id + "'";
                pst = con.prepareStatement(q);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Product successfully deleted");

                try {

                    String sql = "select Product_Id , Medicine_Name, Scientific_Name, Company_Name, Quantity, Product_Category, Manufacure_Date, Expire_Date, Rack_Number from stock ";
                    pst = con.prepareStatement(sql);
                    rst = pst.executeQuery();

                    jTable1.setModel(DbUtils.resultSetToTableModel(rst));

                } catch (SQLException e) {
                }

            } catch (SQLException e) {

            }
            
            }
            else{
            return;
            }
            
            

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.hide();
        home.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_userinfo;
    // End of variables declaration//GEN-END:variables
}
