/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hon2;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author ShredHead
 */
public class ClinicScheduleView extends javax.swing.JFrame {

    /**
     * Creates new form ClinicScheduleView
     * 
     * 
     */
    public MainWindow.Mainwindow home;
    Connection con = null;
    PreparedStatement pst = null;
    public String userNameP;
    public int levelP;
    
    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent (this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
     
    
    public void userInfo (String userName, int level)
    {
        lblUserName.setText("Hello " +userName+ "!");
        userNameP = userName;
        levelP = level;
        if (level == 100)
        {
            lblUserLevel.setText("Level : Admin");
            btnEditSchedule.setVisible(true);
        }
        else if (level == 75)
        {
            lblUserLevel.setText("Level : Doctor");
            btnEditSchedule.setVisible(true);
        }
        else
        {
            btnEditSchedule.setVisible(false);
        }
    }
    
    private void update_table()
    {
        try
        {
            
                String sql1 = "SELECT clinic as Monday FROM clinic_monday";
                pst = con.prepareStatement(sql1);
                ResultSet dates = pst.executeQuery();
                tblMonday.setModel(DbUtils.resultSetToTableModel(dates));
                
                sql1 = "SELECT clinic as Tuesday FROM clinic_tuesday";
                pst = con.prepareStatement(sql1);
                dates = pst.executeQuery();
                tblTuesday.setModel(DbUtils.resultSetToTableModel(dates));
                
                sql1 = "SELECT clinic as Wednesday FROM clinic_wednesday";
                pst = con.prepareStatement(sql1);
                dates = pst.executeQuery();
                tblWednesday.setModel(DbUtils.resultSetToTableModel(dates));
                
                sql1 = "SELECT clinic as Thursday FROM clinic_thursday";
                pst = con.prepareStatement(sql1);
                dates = pst.executeQuery();
                tblThursday.setModel(DbUtils.resultSetToTableModel(dates));
                
                sql1 = "SELECT clinic as Friday FROM clinic_friday";
                pst = con.prepareStatement(sql1);
                dates = pst.executeQuery();
                tblFriday.setModel(DbUtils.resultSetToTableModel(dates));
                
                sql1 = "SELECT clinic as Saturday FROM clinic_saturday";
                pst = con.prepareStatement(sql1);
                dates = pst.executeQuery();
                tblSaturday.setModel(DbUtils.resultSetToTableModel(dates));
                
        }
        catch(Exception eae)
        {
            JOptionPane.showMessageDialog(null,eae);
        }
    }
    public ClinicScheduleView() {
        initComponents();
        con = DBConnect.ConnectDB();
        update_table();
        Date dt = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String datetime = sdf.format(dt);
        jLabel3.setText(datetime);
        taAssignedStaff.disable();
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblSaturday = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblFriday = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblThursday = new javax.swing.JTable();
        btnEditSchedule = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblWednesday = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTuesday = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMonday = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAssignedStaff = new javax.swing.JTextArea();
        lblUserName = new javax.swing.JLabel();
        lblUserLevel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setMinimumSize(new java.awt.Dimension(996, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Clinic Schedule");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 30, 222, 44);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 110, 1000, 10);

        jLabel2.setText("Week starting on :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 80, 140, 14);

        tblSaturday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSaturday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSaturdayMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblSaturday);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(730, 130, 120, 360);

        tblFriday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFriday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFridayMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblFriday);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(610, 130, 120, 360);

        tblThursday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblThursday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThursdayMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblThursday);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(490, 130, 120, 360);

        btnEditSchedule.setText("Edit Schedule");
        btnEditSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditScheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditSchedule);
        btnEditSchedule.setBounds(740, 530, 110, 23);

        tblWednesday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblWednesday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWednesdayMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblWednesday);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(370, 130, 120, 360);

        tblTuesday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTuesday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTuesdayMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTuesday);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(250, 130, 120, 360);

        tblMonday.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMonday.setMaximumSize(new java.awt.Dimension(60, 64));
        tblMonday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMondayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMonday);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 130, 120, 360);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Assigned Staff :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 500, 116, 30);

        taAssignedStaff.setColumns(20);
        taAssignedStaff.setRows(5);
        jScrollPane2.setViewportView(taAssignedStaff);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(130, 530, 373, 96);

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserName.setText("jLabel6");
        getContentPane().add(lblUserName);
        lblUserName.setBounds(790, 40, 110, 15);

        lblUserLevel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserLevel.setText("jLabel6");
        getContentPane().add(lblUserLevel);
        lblUserLevel.setBounds(790, 60, 110, 15);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Profile");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(820, 10, 50, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Logout");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(820, 80, 50, 20);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hon2/admin1.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(920, 10, 60, 80);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hon2/backbtn.jpg"))); // NOI18N
        jButton5.setMaximumSize(new java.awt.Dimension(33, 9));
        jButton5.setMinimumSize(new java.awt.Dimension(33, 9));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 20, 71, 71);

        jLabel3.setText("Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 80, 100, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hon2/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-10, -20, 1070, 790);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditScheduleActionPerformed
        // TODO add your handling code here:
        ClinicScheduleSet clinicset = new ClinicScheduleSet();
        clinicset.userInfo(userNameP, levelP);
        clinicset.setVisible(true);
    }//GEN-LAST:event_btnEditScheduleActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        home.setVisible(true);
        close();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblMondayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMondayMouseClicked
        // TODO add your handling code here:
        tblTuesday.getSelectionModel().clearSelection();
        tblWednesday.getSelectionModel().clearSelection();
        tblThursday.getSelectionModel().clearSelection();
        tblFriday.getSelectionModel().clearSelection();
        tblSaturday.getSelectionModel().clearSelection();
        
        taAssignedStaff.setText("");
        
        int row = tblMonday.getSelectedRow();
        String clinic = (String)tblMonday.getModel().getValueAt(row, 0);
        
        String query = "SELECT Doctor_Name FROM clinic_allocation WHERE Clinic = ?";
        try 
        {
            pst = con.prepareStatement(query);
            pst.setString(1, clinic);
            ResultSet rs = pst.executeQuery();
            String value;
            while(rs.next())
            {
                value = rs.getString("Doctor_Name");
                taAssignedStaff.append(value+ " \n");
            }
            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(LabReportManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblMondayMouseClicked

    private void tblTuesdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTuesdayMouseClicked
        // TODO add your handling code here:
        tblMonday.getSelectionModel().clearSelection();
        tblWednesday.getSelectionModel().clearSelection();
        tblThursday.getSelectionModel().clearSelection();
        tblFriday.getSelectionModel().clearSelection();
        tblSaturday.getSelectionModel().clearSelection();
        
        taAssignedStaff.setText("");
        
        int row = tblTuesday.getSelectedRow();
        String clinic = (String)tblTuesday.getModel().getValueAt(row, 0);
        
        String query = "SELECT Doctor_Name FROM clinic_allocation WHERE Clinic = ?";
        try 
        {
            pst = con.prepareStatement(query);
            pst.setString(1, clinic);
            ResultSet rs = pst.executeQuery();
            String value;
            while(rs.next())
            {
                value = rs.getString("Doctor_Name");
                taAssignedStaff.append(value+ " \n");
            }
            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(LabReportManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblTuesdayMouseClicked

    private void tblWednesdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWednesdayMouseClicked
        // TODO add your handling code here:
        tblMonday.getSelectionModel().clearSelection();
        tblTuesday.getSelectionModel().clearSelection();
        tblThursday.getSelectionModel().clearSelection();
        tblFriday.getSelectionModel().clearSelection();
        tblSaturday.getSelectionModel().clearSelection();
        
        taAssignedStaff.setText("");
        
        int row = tblWednesday.getSelectedRow();
        String clinic = (String)tblWednesday.getModel().getValueAt(row, 0);
        
        String query = "SELECT Doctor_Name FROM clinic_allocation WHERE Clinic = ?";
        try 
        {
            pst = con.prepareStatement(query);
            pst.setString(1, clinic);
            ResultSet rs = pst.executeQuery();
            String value;
            while(rs.next())
            {
                value = rs.getString("Doctor_Name");
                taAssignedStaff.append(value+ " \n");
            }
            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(LabReportManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblWednesdayMouseClicked

    private void tblThursdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThursdayMouseClicked
        // TODO add your handling code here:
        tblMonday.getSelectionModel().clearSelection();
        tblTuesday.getSelectionModel().clearSelection();
        tblWednesday.getSelectionModel().clearSelection();
        tblFriday.getSelectionModel().clearSelection();
        tblSaturday.getSelectionModel().clearSelection();
        
        taAssignedStaff.setText("");
        
        int row = tblThursday.getSelectedRow();
        String clinic = (String)tblThursday.getModel().getValueAt(row, 0);
        
        String query = "SELECT Doctor_Name FROM clinic_allocation WHERE Clinic = ?";
        try 
        {
            pst = con.prepareStatement(query);
            pst.setString(1, clinic);
            ResultSet rs = pst.executeQuery();
            String value;
            while(rs.next())
            {
                value = rs.getString("Doctor_Name");
                taAssignedStaff.append(value+ " \n");
            }
            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(LabReportManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblThursdayMouseClicked

    private void tblFridayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFridayMouseClicked
        // TODO add your handling code here:
        tblMonday.getSelectionModel().clearSelection();
        tblTuesday.getSelectionModel().clearSelection();
        tblWednesday.getSelectionModel().clearSelection();
        tblThursday.getSelectionModel().clearSelection();
        tblSaturday.getSelectionModel().clearSelection();
        
        taAssignedStaff.setText("");
        
        int row = tblFriday.getSelectedRow();
        String clinic = (String)tblFriday.getModel().getValueAt(row, 0);
        
        String query = "SELECT Doctor_Name FROM clinic_allocation WHERE Clinic = ?";
        try 
        {
            pst = con.prepareStatement(query);
            pst.setString(1, clinic);
            ResultSet rs = pst.executeQuery();
            String value;
            while(rs.next())
            {
                value = rs.getString("Doctor_Name");
                taAssignedStaff.append(value+ " \n");
            }
            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(LabReportManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblFridayMouseClicked

    private void tblSaturdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSaturdayMouseClicked
        // TODO add your handling code here:
        tblMonday.getSelectionModel().clearSelection();
        tblTuesday.getSelectionModel().clearSelection();
        tblWednesday.getSelectionModel().clearSelection();
        tblFriday.getSelectionModel().clearSelection();
        tblThursday.getSelectionModel().clearSelection();
        
        taAssignedStaff.setText("");
        
        int row = tblSaturday.getSelectedRow();
        String clinic = (String)tblSaturday.getModel().getValueAt(row, 0);
        
        String query = "SELECT Doctor_Name FROM clinic_allocation WHERE Clinic = ?";
        try 
        {
            pst = con.prepareStatement(query);
            pst.setString(1, clinic);
            ResultSet rs = pst.executeQuery();
            String value;
            while(rs.next())
            {
                value = rs.getString("Doctor_Name");
                taAssignedStaff.append(value+ " \n");
            }
            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(LabReportManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblSaturdayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClinicScheduleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClinicScheduleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClinicScheduleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClinicScheduleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClinicScheduleView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditSchedule;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblUserLevel;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextArea taAssignedStaff;
    private javax.swing.JTable tblFriday;
    private javax.swing.JTable tblMonday;
    private javax.swing.JTable tblSaturday;
    private javax.swing.JTable tblThursday;
    private javax.swing.JTable tblTuesday;
    private javax.swing.JTable tblWednesday;
    // End of variables declaration//GEN-END:variables
}
