/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainWindow;
import Attendace.main;
import hon2.*;
import patient_records_mng_sys.*;
/**
 *
 * @author Alex
 */
public class Mainwindow extends javax.swing.JFrame {
    public StaffManagement.AdminJFrame staff = new StaffManagement.AdminJFrame();
    public staffallocation.extra allocation = new staffallocation.extra();
    public Expenses.main expense = new Expenses.main();
    public Interface.main stock = new Interface.main();
    int level_globle;
    String user_globle;
public login.Login login;
public main attendace = new main();
public LabReportManagement lab_report = new LabReportManagement();
public ClinicScheduleView schedule_view = new ClinicScheduleView();
public EquipmentManagement.main equipment = new EquipmentManagement.main();
public before_one pt_record = new before_one();

    /**
     * Creates new form Mainwindow
     */
     
    public Mainwindow(){
        
        try 
    {
        //LookAndFeel asd = new SyntheticaAluOxideLookAndFeel();
      //UIManager.setLookAndFeel(asd);
    } 
    catch (Exception e) 
    {
      e.printStackTrace();
    }
        initComponents();
        
   
        userinitComponents();
   
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void userinitComponents() {
        attendace.home = this;
        
        
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_expenses = new javax.swing.JButton();
        btn_stock = new javax.swing.JButton();
        btn_patientregistration = new javax.swing.JButton();
        btn_medicle_records = new javax.swing.JButton();
        btn_labreport = new javax.swing.JButton();
        btn_stafflive = new javax.swing.JButton();
        btn_equipmentmanagement = new javax.swing.JButton();
        btn_staffmanagement = new javax.swing.JButton();
        btn_clinic_schedule = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lbl_userinfo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(996, 640));
        setMinimumSize(new java.awt.Dimension(996, 640));
        setPreferredSize(new java.awt.Dimension(996, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(996, 640));
        getContentPane().setLayout(null);

        btn_expenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Finance-512.png"))); // NOI18N
        btn_expenses.setToolTipText("Expense Manager");
        btn_expenses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_expenses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_expenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_expensesMouseClicked(evt);
            }
        });
        btn_expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_expensesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_expenses);
        btn_expenses.setBounds(640, 180, 100, 100);

        btn_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CIB Trade online icon.PNG"))); // NOI18N
        btn_stock.setToolTipText("Stock Management System");
        btn_stock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stockMouseClicked(evt);
            }
        });
        btn_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stockActionPerformed(evt);
            }
        });
        getContentPane().add(btn_stock);
        btn_stock.setBounds(750, 380, 100, 100);

        btn_patientregistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Staff (1).png"))); // NOI18N
        btn_patientregistration.setToolTipText("Patiend Registration and Attendace System");
        btn_patientregistration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_patientregistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_patientregistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_patientregistrationMouseClicked(evt);
            }
        });
        btn_patientregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_patientregistrationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_patientregistration);
        btn_patientregistration.setBounds(20, 180, 100, 100);

        btn_medicle_records.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainWindow/Medical Records.png"))); // NOI18N
        btn_medicle_records.setToolTipText("Patient Record Management System");
        btn_medicle_records.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_medicle_records.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_medicle_records.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_medicle_recordsMouseClicked(evt);
            }
        });
        btn_medicle_records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_medicle_recordsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_medicle_records);
        btn_medicle_records.setBounds(220, 180, 100, 100);

        btn_labreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laboratory-512.png"))); // NOI18N
        btn_labreport.setToolTipText("Lab Report Management");
        btn_labreport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_labreport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_labreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_labreportMouseClicked(evt);
            }
        });
        btn_labreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_labreportActionPerformed(evt);
            }
        });
        getContentPane().add(btn_labreport);
        btn_labreport.setBounds(440, 180, 100, 100);

        btn_stafflive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab_report.png"))); // NOI18N
        btn_stafflive.setToolTipText("Staff allocation and Live data Monitoring");
        btn_stafflive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_stafflive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_stafflive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_staffliveMouseClicked(evt);
            }
        });
        btn_stafflive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staffliveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_stafflive);
        btn_stafflive.setBounds(120, 380, 100, 100);

        btn_equipmentmanagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sb_scheduling.png"))); // NOI18N
        btn_equipmentmanagement.setToolTipText("Equipment Management System");
        btn_equipmentmanagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_equipmentmanagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_equipmentmanagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_equipmentmanagementMouseClicked(evt);
            }
        });
        btn_equipmentmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equipmentmanagementActionPerformed(evt);
            }
        });
        getContentPane().add(btn_equipmentmanagement);
        btn_equipmentmanagement.setBounds(340, 380, 100, 100);

        btn_staffmanagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendance_list_icon.png"))); // NOI18N
        btn_staffmanagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_staffmanagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_staffmanagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_staffmanagementMouseClicked(evt);
            }
        });
        btn_staffmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staffmanagementActionPerformed(evt);
            }
        });
        getContentPane().add(btn_staffmanagement);
        btn_staffmanagement.setBounds(550, 380, 100, 100);

        btn_clinic_schedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/allocation.png"))); // NOI18N
        btn_clinic_schedule.setToolTipText("Clinic Schedule Management");
        btn_clinic_schedule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_clinic_schedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clinic_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clinic_scheduleMouseClicked(evt);
            }
        });
        btn_clinic_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clinic_scheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clinic_schedule);
        btn_clinic_schedule.setBounds(850, 180, 100, 100);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 100, 1000, 10);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Attendace/home.png"))); // NOI18N
        jButton10.setToolTipText("");
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(10, 10, 70, 70);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Logout");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(780, 70, 50, 20);

        lbl_userinfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_userinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_userinfo.setText("<html>Hello Sleepy!<br> level : Admin </html>");
        getContentPane().add(lbl_userinfo);
        lbl_userinfo.setBounds(690, 30, 240, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Profile");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(780, 10, 50, 20);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Attendace/admin1.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(900, 10, 60, 80);

        jLabel11.setBackground(new java.awt.Color(0, 153, 0));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Logged In !");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 590, 1010, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Menu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 30, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/11806788_1135526379794041_692436290_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(996, 640));
        jLabel1.setMinimumSize(new java.awt.Dimension(996, 640));
        jLabel1.setPreferredSize(new java.awt.Dimension(996, 640));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void setUserDetails(String Username, int level){
         level_globle = level;
         user_globle = Username;
         if(level==100){
            lbl_userinfo.setText("<html>Hello "+Username+"<br> Level : Admin </html>");
            btn_clinic_schedule.setEnabled(true);
            btn_equipmentmanagement.setEnabled(true);
            btn_expenses.setEnabled(true);
            btn_labreport.setEnabled(true);
            btn_medicle_records.setEnabled(true);
            btn_patientregistration.setEnabled(true);
            btn_stafflive.setEnabled(true);
            btn_staffmanagement.setEnabled(true);
            btn_stock.setEnabled(true);
        }else if(level==75){
            lbl_userinfo.setText("<html>Hello "+Username+"<br> Level : Doctor </html>");
            btn_clinic_schedule.setEnabled(false);
            btn_equipmentmanagement.setEnabled(false);
            btn_expenses.setEnabled(false);
            btn_labreport.setEnabled(true);
            btn_medicle_records.setEnabled(true);
            btn_patientregistration.setEnabled(true);
            btn_stafflive.setEnabled(true);
            btn_staffmanagement.setEnabled(false);
            btn_stock.setEnabled(false);
        }else if(level==65){
            lbl_userinfo.setText("<html>Hello "+Username+"<br> Level : Nurse/Receptionist </html>");
            
            btn_clinic_schedule.setEnabled(false);
            btn_equipmentmanagement.setEnabled(false);
            btn_expenses.setEnabled(false);
            btn_labreport.setEnabled(false);
            btn_medicle_records.setEnabled(false);
            btn_patientregistration.setEnabled(true);
            btn_stafflive.setEnabled(true);
            btn_staffmanagement.setEnabled(false);
            btn_stock.setEnabled(false);
        }
    
    }
    private void btn_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stockMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_stockMouseClicked

    private void btn_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stockActionPerformed
        // TODO add your handling code here:
        this.hide();
        stock.show();
        stock.home = this;
        stock.hello = lbl_userinfo.getText();
        stock.login = login;
        
    }//GEN-LAST:event_btn_stockActionPerformed

    private void btn_patientregistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_patientregistrationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_patientregistrationMouseClicked

    private void btn_patientregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_patientregistrationActionPerformed
        // TODO add your handling code here:
        this.hide();
        attendace.show();
        attendace.home = this;
        attendace.setUserDetails(user_globle, level_globle);
        attendace.login = login;
    }//GEN-LAST:event_btn_patientregistrationActionPerformed

    private void btn_expensesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_expensesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_expensesMouseClicked

    private void btn_expensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_expensesActionPerformed
        // TODO add your handling code here:
        this.hide();
        expense.setVisible(true);
        expense.home = this;
        expense.setUserDetails(user_globle, level_globle);
        expense.login = login;
    }//GEN-LAST:event_btn_expensesActionPerformed

    private void btn_medicle_recordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_medicle_recordsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_medicle_recordsMouseClicked

    private void btn_medicle_recordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_medicle_recordsActionPerformed
        // TODO add your handling code here:
        pt_record.setUserGroup(user_globle, level_globle);
        pt_record.setVisible(true);
        pt_record.home = this;
        
        this.hide();
        
    }//GEN-LAST:event_btn_medicle_recordsActionPerformed

    private void btn_labreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_labreportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_labreportMouseClicked

    private void btn_labreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_labreportActionPerformed
        // TODO add your handling code here:
        
        lab_report.setVisible(true);
        lab_report.home = this;
        lab_report.userInfo(user_globle, level_globle);
        this.setVisible(false);
    }//GEN-LAST:event_btn_labreportActionPerformed

    private void btn_staffliveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_staffliveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_staffliveMouseClicked

    private void btn_staffliveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staffliveActionPerformed
        // TODO add your handling code here:
        this.hide();
        allocation.setVisible(true);
        allocation.home = this;
        allocation.setUserDetails(user_globle, level_globle);
    }//GEN-LAST:event_btn_staffliveActionPerformed

    private void btn_equipmentmanagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_equipmentmanagementMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_equipmentmanagementMouseClicked

    private void btn_equipmentmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equipmentmanagementActionPerformed
        // TODO add your handling code here:
        
        equipment.home = this;
        equipment.setVisible(true);
        this.hide();
        equipment.setUserDetails(user_globle, level_globle);
        equipment.login = login;
        //herer
    }//GEN-LAST:event_btn_equipmentmanagementActionPerformed

    private void btn_staffmanagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_staffmanagementMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_staffmanagementMouseClicked

    private void btn_staffmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staffmanagementActionPerformed
        // TODO add your handling code here:
        staff.setVisible(true);
        this.hide();
        staff.home = this;
    }//GEN-LAST:event_btn_staffmanagementActionPerformed

    private void btn_clinic_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clinic_scheduleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clinic_scheduleMouseClicked

    private void btn_clinic_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clinic_scheduleActionPerformed
        // TODO add your handling code here:
        schedule_view.setVisible(true);
        schedule_view.home = this;
        schedule_view.userInfo(user_globle, level_globle);
        this.hide();
    }//GEN-LAST:event_btn_clinic_scheduleActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new Mainwindow().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clinic_schedule;
    private javax.swing.JButton btn_equipmentmanagement;
    private javax.swing.JButton btn_expenses;
    private javax.swing.JButton btn_labreport;
    private javax.swing.JButton btn_medicle_records;
    private javax.swing.JButton btn_patientregistration;
    private javax.swing.JButton btn_stafflive;
    private javax.swing.JButton btn_staffmanagement;
    private javax.swing.JButton btn_stock;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_userinfo;
    // End of variables declaration//GEN-END:variables
}
