package StaffManagement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Alex
 */
public class AddStaffMember extends parent {

    /**
     * Creates new form main
     */
    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs=null;
    char array[] = new char[4];

    private void refresh() {
        txtuname.setText(null);
        txtaddress.setText(null);
        txtfname.setText(null);
        txtfurther.setText(null);
        txtgrade.setText(null);
        txtpass.setText(null);
        txtphone.setText(null);
        txtspecial.setText(null);
        txtannual.setText(null);
        cmbdesignation.setSelectedItem("Designation");
        cmbsupportstaff.setSelectedItem("Support Staff");
        cmblevel.setSelectedItem("Other Staff");
        rdomale.setSelected(true);

    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    public AddStaffMember() {
        this.setResizable(true);
        initComponents();
        con = DBConnect.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtgrade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rdofemale = new javax.swing.JRadioButton();
        txtfurther = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbdesignation = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtspecial = new javax.swing.JTextField();
        rdomale = new javax.swing.JRadioButton();
        txtannual = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbsupportstaff = new javax.swing.JComboBox();
        joindate = new com.toedter.calendar.JDateChooser();
        cmblevel = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel23 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipment Management System");
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(java.awt.SystemColor.activeCaptionText);
        setMinimumSize(new java.awt.Dimension(1500, 690));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 100, 1000, 10);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Attendace/admin1.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(930, 10, 60, 80);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Logout");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(830, 70, 50, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Hello");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(820, 30, 100, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Profile");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(830, 10, 50, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Attendace/home.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 73, 60);

        jLabel9.setText("Grade");
        jLabel9.setName("lblname"); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(610, 250, 110, 14);

        txtgrade.setName("txtGrade"); // NOI18N
        getContentPane().add(txtgrade);
        txtgrade.setBounds(690, 240, 210, 30);

        jLabel7.setText("Level");
        jLabel7.setName("lblname"); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(680, 140, 60, 20);

        rdofemale.setText("Female");
        rdofemale.setName("radioFemale"); // NOI18N
        getContentPane().add(rdofemale);
        rdofemale.setBounds(440, 220, 90, 23);

        txtfurther.setName("txtFurther"); // NOI18N
        getContentPane().add(txtfurther);
        txtfurther.setBounds(330, 380, 210, 30);

        jLabel6.setText("Gender");
        jLabel6.setName("lblname"); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 220, 80, 14);

        jLabel4.setText("Specialization");
        jLabel4.setName("lblname"); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 350, 90, 14);

        txtphone.setName("txtPhoneNumber"); // NOI18N
        getContentPane().add(txtphone);
        txtphone.setBounds(330, 300, 210, 30);

        txtaddress.setName("txtaddress"); // NOI18N
        getContentPane().add(txtaddress);
        txtaddress.setBounds(330, 260, 210, 30);

        jLabel2.setText("Address");
        jLabel2.setName("lblname"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 270, 70, 14);

        cmbdesignation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Designation", "Doctor", "Nurse", "Support Staff", "" }));
        cmbdesignation.setName("cmbDesignation"); // NOI18N
        cmbdesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdesignationActionPerformed(evt);
            }
        });
        getContentPane().add(cmbdesignation);
        cmbdesignation.setBounds(200, 140, 190, 20);

        jButton3.setText("Add Staff Member");
        jButton3.setName("btnAddStaff"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 480, 160, 50);

        jLabel8.setText("Further Specialization");
        jLabel8.setName("lblname"); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 390, 130, 14);

        txtspecial.setName("txtSpecial"); // NOI18N
        txtspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspecialActionPerformed(evt);
            }
        });
        getContentPane().add(txtspecial);
        txtspecial.setBounds(330, 340, 210, 30);

        rdomale.setText("Male");
        rdomale.setName("radioMale"); // NOI18N
        rdomale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdomaleActionPerformed(evt);
            }
        });
        getContentPane().add(rdomale);
        rdomale.setBounds(330, 220, 80, 23);

        txtannual.setName("txtannual"); // NOI18N
        getContentPane().add(txtannual);
        txtannual.setBounds(330, 430, 210, 30);

        jLabel10.setText("Full Name");
        jLabel10.setName("lblname"); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(180, 190, 80, 10);

        jLabel16.setText("You are Logged in as an Admin");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(710, 110, 180, 14);

        jLabel3.setText("Phone Number");
        jLabel3.setName("lblname"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 310, 100, 14);

        jLabel5.setText("Join Date");
        jLabel5.setName("lblname"); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(610, 190, 110, 20);

        txtfname.setName("txtfname"); // NOI18N
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfname);
        txtfname.setBounds(330, 180, 210, 30);

        jLabel11.setText("Annual Salary");
        jLabel11.setName("lblname"); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 440, 130, 20);

        cmbsupportstaff.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Support Staff", "Receptionist", "Clerk", "Cleaner" }));
        cmbsupportstaff.setEnabled(false);
        getContentPane().add(cmbsupportstaff);
        cmbsupportstaff.setBounds(490, 140, 100, 20);

        joindate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(joindate);
        joindate.setBounds(690, 190, 210, 30);

        cmblevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Other Staff", "Admin", "Doctor", "Nurse", "Receptionist", "Office Staff" }));
        cmblevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmblevelActionPerformed(evt);
            }
        });
        getContentPane().add(cmblevel);
        cmblevel.setBounds(720, 140, 100, 20);

        jLabel17.setText("Username");
        jLabel17.setName("lblname"); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(610, 300, 60, 20);

        txtuname.setName("txtuname"); // NOI18N
        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });
        getContentPane().add(txtuname);
        txtuname.setBounds(690, 290, 210, 30);

        jLabel18.setText("Password");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(610, 350, 90, 14);

        txtpass.setText("jPasswordField1");
        getContentPane().add(txtpass);
        txtpass.setBounds(690, 350, 111, 20);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StaffManagement/11754783_1132556243424388_4078586450580011341_o.jpg"))); // NOI18N
        jLabel23.setText("jLabel23");
        jLabel23.setToolTipText("");
        jLabel23.setMinimumSize(new java.awt.Dimension(600, 550));
        jLabel23.setPreferredSize(new java.awt.Dimension(1400, 600));
        getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 1400, 660);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspecialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspecialActionPerformed
public static String strnext(String s) {
   int l = s.length();
   int num;
        num = Integer.parseInt(s.substring(1, l));
 
   String result;
   result=("e"+(num+1));
   return result;
 }
public static String strnext2(String s) {
   int l = s.length();
   int num;
        num = Integer.parseInt(s.substring(2, l));
 
   String result;
   result=("ad"+(num+1));
   return result;
 }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String fn = txtfname.getText().trim();
        String add = txtaddress.getText().trim();
        String phone = txtphone.getText().trim();
        String sp = txtspecial.getText().trim();
        String further = txtfurther.getText().trim();
        String ann = txtannual.getText().trim();
        String grade = txtgrade.getText().trim();
        String designation = (String) cmbdesignation.getSelectedItem();
        String lvl = (String) cmblevel.getSelectedItem();
        String uname = txtuname.getText().trim();
        
        String gend = null;
        String pass = txtpass.getText();
        
        if (rdomale.isSelected()) {
            gend = "M";
        } else if (rdofemale.isSelected()) {
            gend = "F";
        }
        
        int level;

        switch (lvl.toLowerCase()) {
            case "admin":
                level = 100;
                break;
            case "doctor":
                level = 75;
                break;
            case "nurse":
                level = 60;
                break;
            case "receptionist":
                level = 4;
                break;
            case "office":
                level = 50;
                break;
            default:
                level = 50;
                break;
        }
        String str = null;

        try {
             String sq="SELECT employeeNo FROM employee ORDER BY employeeNo DESC LIMIT 1";
       
            pst = con.prepareStatement(sq);
            rs = pst.executeQuery();
        

            while (rs.next()) {
            str=rs.getString("employeeNo");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddStaffMember.class.getName()).log(Level.SEVERE, null, ex);
        }
        String at=null;
         try {
             String sqr="SELECT attendaceNo FROM employee ORDER BY employeeNo DESC LIMIT 1";
       
            pst = con.prepareStatement(sqr);
            rs = pst.executeQuery();
        

            while (rs.next()) {
            at=rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddStaffMember.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String empid=strnext(str);
        String attendno=strnext2(at);
        if(rdofemale.isSelected()||rdomale.isSelected()){
        if ((fn.length() != 0) && (phone.length() != 0) && (pass.length() != 0) && (add.length() != 0)) {
            if (uname.length() != 0) {
                if ((pass.length() != 0)) {

                    if (designation == "Doctor") {
                        try {
                            String q = "INSERT INTO employee (employeeNo,attendaceNo,anualSalary,phone,name,address,join_date,employee_type,level,gender) values ('"+empid+"','"+attendno+"',?,?,?,?,?,'D',?,?)";
                            pst = con.prepareStatement(q);
                            pst.setString(1, ann);
                            pst.setString(2, phone);
                            pst.setString(3, fn);
                            pst.setString(4, add);
                            pst.setString(5, ((JTextField) joindate.getDateEditor().getUiComponent()).getText());
                            pst.setInt(6, level);
                            pst.setString(7, gend);
                            pst.execute();
                            pst.close();
                        } catch (SQLException ex1) {
                            Logger.getLogger(AddStaffMember.class.getName()).log(Level.SEVERE, null, ex1);
                        }

                        try {
                            String p = "INSERT INTO doctor (employeeNo,furtherSpecialitation,specialitation) values ('"+empid+"',?,?)";
                            pst1 = con.prepareStatement(p);
                            pst1.setString(1, further);
                            pst1.setString(2, sp);
                            pst1.execute();
                            pst1.close();

                        } catch (SQLException ex1) {
                            Logger.getLogger(AddStaffMember.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                        try {
                            String p = "INSERT INTO login (employeeNo,user_name,pass_word,level) values ('"+empid+"',?,?,?)";
                            pst1 = con.prepareStatement(p);
                            pst1.setString(1, uname);
                            pst1.setString(2, pass);
                            pst1.setInt(3, level);
                            pst1.execute();
                            pst1.close();
                            JOptionPane.showMessageDialog(null, "Details of the Doctor was added");
                            refresh();    
                        } catch (SQLException ex1) {
                            Logger.getLogger(AddStaffMember.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                    } else if (designation == "Nurse") {
                        try {
                             String q = "INSERT INTO employee (employeeNo,attendaceNo,anualSalary,phone,name,address,join_date,employee_type,level,gender) values ('"+empid+"','"+attendno+"',?,?,?,?,?,'D',?,?)";

                            pst = con.prepareStatement(q);
                            pst.setString(1, ann);
                            pst.setString(2, phone);
                            pst.setString(3, fn);
                            pst.setString(4, add);
                            pst.setString(5, ((JTextField) joindate.getDateEditor().getUiComponent()).getText());
                            pst.setInt(6, level);
                            pst.setString(7, gend);
                            pst.execute();
                            pst.close();
                        } catch (SQLException ex1) {
                            Logger.getLogger(AddStaffMember.class.getName()).log(Level.SEVERE, null, ex1);
                        }

                        try {
                            String p = "INSERT INTO nurse (employeeNo,grade) values ('"+empid+"',?)";
                            pst1 = con.prepareStatement(p);
                            pst1.setString(1, grade);
                            pst1.execute();
                            pst1.close();
                            

                        } catch (SQLException ex1) {
                            Logger.getLogger(AddStaffMember.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                        try {
                            String p = "INSERT INTO login (employeeNo,user_name,pass_word,level) values ('"+empid+"',?,?,?)";
                            pst1 = con.prepareStatement(p);
                            pst1.setString(1, uname);
                            pst1.setString(2, pass);
                            pst1.setInt(3, level);
                            pst1.execute();
                            pst1.close();
                            JOptionPane.showMessageDialog(null, "Details of the Nurse was added");
                              refresh();
                        } catch (SQLException ex1) {
                            Logger.getLogger(AddStaffMember.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                    } else if (designation == "Support Staff") {
                        String suppstaff = (String) cmbsupportstaff.getSelectedItem();
                        try {
                             String q = "INSERT INTO employee (employeeNo,attendaceNo,anualSalary,phone,name,address,join_date,employee_type,level,gender) values ('"+empid+"','"+attendno+"',?,?,?,?,?,'D',?,?)";
                            pst = con.prepareStatement(q);
                            pst.setString(1, ann);
                            pst.setString(2, phone);
                            pst.setString(3, fn);
                            pst.setString(4, add);
                            pst.setString(5, ((JTextField) joindate.getDateEditor().getUiComponent()).getText());
                            pst.setInt(6, level);
                            pst.setString(7, gend);
                            pst.execute();
                            pst.close();
                        } catch (SQLException ex1) {
                            Logger.getLogger(AddStaffMember.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                        try {
                            String p = "INSERT INTO supportstaff (employeeNo,staffType) values ('"+empid+"',?)";
                            pst1 = con.prepareStatement(p);
                            pst1.setString(1, suppstaff);
                            pst1.execute();
                            pst1.close();

                        } catch (SQLException ex1) {
                            Logger.getLogger(AddStaffMember.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                        try {
                            String p = "INSERT INTO login (employeeNo,user_name,pass_word,level) values ('"+empid+"',?,?,?)";
                            pst1 = con.prepareStatement(p);
                            pst1.setString(1, uname);
                            pst1.setString(2, pass);
                            pst1.setInt(3, level);
                            pst1.execute();
                            pst1.close();
                            JOptionPane.showMessageDialog(null, "Details of the Staff Member was added");
                            refresh();
                        } catch (SQLException ex1) {
                            Logger.getLogger(AddStaffMember.class.getName()).log(Level.SEVERE, null, ex1);
                        }

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Password is invalid.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Username cannot be empty.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Username/First Name/Last Name.");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Select your gender");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbdesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdesignationActionPerformed

        // TODO add your handling code here:
        String designation = (String) cmbdesignation.getSelectedItem();
        if ("Support Staff".equals(designation)) {
            cmbsupportstaff.setEnabled(true);

            txtfurther.setEnabled(false);
            txtspecial.setEnabled(false);
            txtgrade.setEnabled(false);
            txtfurther.setEditable(false);
            txtspecial.setEditable(false);
            txtgrade.setEditable(false);

        } else if ("Doctor".equals(designation)) {

            txtgrade.setEnabled(false);

            txtgrade.setEditable(false);
            txtfurther.setEditable(true);
            txtspecial.setEditable(true);
            txtfurther.setEnabled(true);
            txtspecial.setEnabled(true);

        } else if ("Nurse".equals(designation)) {
            txtfurther.setEnabled(false);
            txtspecial.setEnabled(false);

            txtfurther.setEditable(false);
            txtspecial.setEditable(false);

            txtgrade.setEditable(true);
            txtgrade.setEnabled(true);

        } else {
            cmbsupportstaff.setEnabled(false);
            txtfurther.setEnabled(false);
            txtspecial.setEnabled(false);
            txtgrade.setEnabled(false);
            txtfurther.setEditable(false);
            txtspecial.setEditable(false);
            txtgrade.setEditable(false);
        }

    }//GEN-LAST:event_cmbdesignationActionPerformed

    private void cmblevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmblevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmblevelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AdminJFrame ajf = new AdminJFrame();
        ajf.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunameActionPerformed

    private void rdomaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdomaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdomaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStaffMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStaffMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStaffMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStaffMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddStaffMember().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbdesignation;
    private javax.swing.JComboBox cmblevel;
    private javax.swing.JComboBox cmbsupportstaff;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JDateChooser joindate;
    private javax.swing.JRadioButton rdofemale;
    private javax.swing.JRadioButton rdomale;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtannual;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtfurther;
    private javax.swing.JTextField txtgrade;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtspecial;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables

    private void trigger(String reset) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
